# Simple Matrix Operations

In [0]:
import numpy as np

Define a matrix X 

In [0]:
X = np.matrix([[0.1,0.5,0.3],[0.2,0.1,0.5],[0.4,0.5,0.1]])
print("Matrix X = ")
print(X)

Matrix X = 
[[0.1 0.5 0.3]
 [0.2 0.1 0.5]
 [0.4 0.5 0.1]]


Define a class called Neuron

In the constructor, define a matrix called W and initialize all elements to be 0.1. The size of the matrix is the parameters from the constructor

Define a method called addColumn that adds a column whose elements are all one to the first column 

Define a method called compute that calculates the following equation where * dnotes a matrix muliplication


$\huge{\frac{1}{1 + \exp^{-X * W}}}$


In [0]:
## For exp(X), use np.exp(X)
class Neuron:

  def __init__(self, n, m):
    self.W = np.ones([n,m]) * 0.1

  def addColumn(self, X):
    X0 = np.ones(np.shape(X)[0])
    return (np.column_stack((X0, X)))

  def compute(self, X):
    return (1/(1+(np.exp(np.dot(X, self.W)*-1))))

  def print(self):
    print(self.W)

Perform the following computation

In [0]:
m = Neuron(1+3,3)

print('Matrix W = ')
m.print()

X2 = m.addColumn(X)
print('Added Column Matrix = ')
print(X2)

X3 = m.compute(X2)
print('Computed Matrix = ')
print(X3)


X4 = m.addColumn(X3)
print('Added Column Matrix = ')
print(X4)

X5 = m.compute(X4)
print('Computed Matrix = ')
print(X5)

Matrix W = 
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
Added Column Matrix = 
[[1.  0.1 0.5 0.3]
 [1.  0.2 0.1 0.5]
 [1.  0.4 0.5 0.1]]
Computed Matrix = 
[[0.54735762 0.54735762 0.54735762]
 [0.54487889 0.54487889 0.54487889]
 [0.549834   0.549834   0.549834  ]]
Added Column Matrix = 
[[1.         0.54735762 0.54735762 0.54735762]
 [1.         0.54487889 0.54487889 0.54487889]
 [1.         0.549834   0.549834   0.549834  ]]
Computed Matrix = 
[[0.56567025 0.56567025 0.56567025]
 [0.56548755 0.56548755 0.56548755]
 [0.56585277 0.56585277 0.56585277]]
